// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_Game.proto

#ifndef PROTOBUF_Msg_5fGame_2eproto__INCLUDED
#define PROTOBUF_Msg_5fGame_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Msg_5fGame_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsCreateNewSceneReqImpl();
void InitDefaultsCreateNewSceneReq();
void InitDefaultsCreateNewSceneAckImpl();
void InitDefaultsCreateNewSceneAck();
void InitDefaultsEnterSceneReqImpl();
void InitDefaultsEnterSceneReq();
void InitDefaultsEnterSceneAckImpl();
void InitDefaultsEnterSceneAck();
void InitDefaultsLeaveSceneReqImpl();
void InitDefaultsLeaveSceneReq();
void InitDefaultsLeaveSceneAckImpl();
void InitDefaultsLeaveSceneAck();
inline void InitDefaults() {
  InitDefaultsCreateNewSceneReq();
  InitDefaultsCreateNewSceneAck();
  InitDefaultsEnterSceneReq();
  InitDefaultsEnterSceneAck();
  InitDefaultsLeaveSceneReq();
  InitDefaultsLeaveSceneAck();
}
}  // namespace protobuf_Msg_5fGame_2eproto
class CreateNewSceneAck;
class CreateNewSceneAckDefaultTypeInternal;
extern CreateNewSceneAckDefaultTypeInternal _CreateNewSceneAck_default_instance_;
class CreateNewSceneReq;
class CreateNewSceneReqDefaultTypeInternal;
extern CreateNewSceneReqDefaultTypeInternal _CreateNewSceneReq_default_instance_;
class EnterSceneAck;
class EnterSceneAckDefaultTypeInternal;
extern EnterSceneAckDefaultTypeInternal _EnterSceneAck_default_instance_;
class EnterSceneReq;
class EnterSceneReqDefaultTypeInternal;
extern EnterSceneReqDefaultTypeInternal _EnterSceneReq_default_instance_;
class LeaveSceneAck;
class LeaveSceneAckDefaultTypeInternal;
extern LeaveSceneAckDefaultTypeInternal _LeaveSceneAck_default_instance_;
class LeaveSceneReq;
class LeaveSceneReqDefaultTypeInternal;
extern LeaveSceneReqDefaultTypeInternal _LeaveSceneReq_default_instance_;

// ===================================================================

class CreateNewSceneReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CreateNewSceneReq) */ {
 public:
  CreateNewSceneReq();
  virtual ~CreateNewSceneReq();

  CreateNewSceneReq(const CreateNewSceneReq& from);

  inline CreateNewSceneReq& operator=(const CreateNewSceneReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateNewSceneReq(CreateNewSceneReq&& from) noexcept
    : CreateNewSceneReq() {
    *this = ::std::move(from);
  }

  inline CreateNewSceneReq& operator=(CreateNewSceneReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateNewSceneReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateNewSceneReq* internal_default_instance() {
    return reinterpret_cast<const CreateNewSceneReq*>(
               &_CreateNewSceneReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CreateNewSceneReq* other);
  friend void swap(CreateNewSceneReq& a, CreateNewSceneReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateNewSceneReq* New() const PROTOBUF_FINAL { return New(NULL); }

  CreateNewSceneReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CreateNewSceneReq& from);
  void MergeFrom(const CreateNewSceneReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CreateNewSceneReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 CopyID = 1;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 1;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // int32 CopyType = 2;
  void clear_copytype();
  static const int kCopyTypeFieldNumber = 2;
  ::google::protobuf::int32 copytype() const;
  void set_copytype(::google::protobuf::int32 value);

  // uint64 CreateParam = 4;
  void clear_createparam();
  static const int kCreateParamFieldNumber = 4;
  ::google::protobuf::uint64 createparam() const;
  void set_createparam(::google::protobuf::uint64 value);

  // int32 PlayerNum = 3;
  void clear_playernum();
  static const int kPlayerNumFieldNumber = 3;
  ::google::protobuf::int32 playernum() const;
  void set_playernum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CreateNewSceneReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 copyid_;
  ::google::protobuf::int32 copytype_;
  ::google::protobuf::uint64 createparam_;
  ::google::protobuf::int32 playernum_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fGame_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fGame_2eproto::InitDefaultsCreateNewSceneReqImpl();
};
// -------------------------------------------------------------------

class CreateNewSceneAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CreateNewSceneAck) */ {
 public:
  CreateNewSceneAck();
  virtual ~CreateNewSceneAck();

  CreateNewSceneAck(const CreateNewSceneAck& from);

  inline CreateNewSceneAck& operator=(const CreateNewSceneAck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateNewSceneAck(CreateNewSceneAck&& from) noexcept
    : CreateNewSceneAck() {
    *this = ::std::move(from);
  }

  inline CreateNewSceneAck& operator=(CreateNewSceneAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateNewSceneAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateNewSceneAck* internal_default_instance() {
    return reinterpret_cast<const CreateNewSceneAck*>(
               &_CreateNewSceneAck_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(CreateNewSceneAck* other);
  friend void swap(CreateNewSceneAck& a, CreateNewSceneAck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateNewSceneAck* New() const PROTOBUF_FINAL { return New(NULL); }

  CreateNewSceneAck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CreateNewSceneAck& from);
  void MergeFrom(const CreateNewSceneAck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CreateNewSceneAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // int32 CopyID = 2;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 2;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // uint64 CreateParam = 4;
  void clear_createparam();
  static const int kCreateParamFieldNumber = 4;
  ::google::protobuf::uint64 createparam() const;
  void set_createparam(::google::protobuf::uint64 value);

  // int32 CopyGuid = 3;
  void clear_copyguid();
  static const int kCopyGuidFieldNumber = 3;
  ::google::protobuf::int32 copyguid() const;
  void set_copyguid(::google::protobuf::int32 value);

  // int32 ServerID = 5;
  void clear_serverid();
  static const int kServerIDFieldNumber = 5;
  ::google::protobuf::int32 serverid() const;
  void set_serverid(::google::protobuf::int32 value);

  // int32 CopyType = 6;
  void clear_copytype();
  static const int kCopyTypeFieldNumber = 6;
  ::google::protobuf::int32 copytype() const;
  void set_copytype(::google::protobuf::int32 value);

  // int32 PlayerNum = 7;
  void clear_playernum();
  static const int kPlayerNumFieldNumber = 7;
  ::google::protobuf::int32 playernum() const;
  void set_playernum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CreateNewSceneAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 retcode_;
  ::google::protobuf::int32 copyid_;
  ::google::protobuf::uint64 createparam_;
  ::google::protobuf::int32 copyguid_;
  ::google::protobuf::int32 serverid_;
  ::google::protobuf::int32 copytype_;
  ::google::protobuf::int32 playernum_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fGame_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fGame_2eproto::InitDefaultsCreateNewSceneAckImpl();
};
// -------------------------------------------------------------------

class EnterSceneReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EnterSceneReq) */ {
 public:
  EnterSceneReq();
  virtual ~EnterSceneReq();

  EnterSceneReq(const EnterSceneReq& from);

  inline EnterSceneReq& operator=(const EnterSceneReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EnterSceneReq(EnterSceneReq&& from) noexcept
    : EnterSceneReq() {
    *this = ::std::move(from);
  }

  inline EnterSceneReq& operator=(EnterSceneReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const EnterSceneReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnterSceneReq* internal_default_instance() {
    return reinterpret_cast<const EnterSceneReq*>(
               &_EnterSceneReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(EnterSceneReq* other);
  friend void swap(EnterSceneReq& a, EnterSceneReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EnterSceneReq* New() const PROTOBUF_FINAL { return New(NULL); }

  EnterSceneReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EnterSceneReq& from);
  void MergeFrom(const EnterSceneReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EnterSceneReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // int32 ServerID = 2;
  void clear_serverid();
  static const int kServerIDFieldNumber = 2;
  ::google::protobuf::int32 serverid() const;
  void set_serverid(::google::protobuf::int32 value);

  // int32 CopyGuid = 3;
  void clear_copyguid();
  static const int kCopyGuidFieldNumber = 3;
  ::google::protobuf::int32 copyguid() const;
  void set_copyguid(::google::protobuf::int32 value);

  // int32 CopyID = 4;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 4;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:EnterSceneReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::int32 serverid_;
  ::google::protobuf::int32 copyguid_;
  ::google::protobuf::int32 copyid_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fGame_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fGame_2eproto::InitDefaultsEnterSceneReqImpl();
};
// -------------------------------------------------------------------

class EnterSceneAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EnterSceneAck) */ {
 public:
  EnterSceneAck();
  virtual ~EnterSceneAck();

  EnterSceneAck(const EnterSceneAck& from);

  inline EnterSceneAck& operator=(const EnterSceneAck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EnterSceneAck(EnterSceneAck&& from) noexcept
    : EnterSceneAck() {
    *this = ::std::move(from);
  }

  inline EnterSceneAck& operator=(EnterSceneAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const EnterSceneAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnterSceneAck* internal_default_instance() {
    return reinterpret_cast<const EnterSceneAck*>(
               &_EnterSceneAck_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(EnterSceneAck* other);
  friend void swap(EnterSceneAck& a, EnterSceneAck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EnterSceneAck* New() const PROTOBUF_FINAL { return New(NULL); }

  EnterSceneAck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EnterSceneAck& from);
  void MergeFrom(const EnterSceneAck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EnterSceneAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 Equips = 17;
  int equips_size() const;
  void clear_equips();
  static const int kEquipsFieldNumber = 17;
  ::google::protobuf::int32 equips(int index) const;
  void set_equips(int index, ::google::protobuf::int32 value);
  void add_equips(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      equips() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_equips();

  // string RoleName = 7;
  void clear_rolename();
  static const int kRoleNameFieldNumber = 7;
  const ::std::string& rolename() const;
  void set_rolename(const ::std::string& value);
  #if LANG_CXX11
  void set_rolename(::std::string&& value);
  #endif
  void set_rolename(const char* value);
  void set_rolename(const char* value, size_t size);
  ::std::string* mutable_rolename();
  ::std::string* release_rolename();
  void set_allocated_rolename(::std::string* rolename);

  // uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // int32 CopyID = 2;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 2;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // uint64 RoleID = 4;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 4;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // int32 CopyGuid = 3;
  void clear_copyguid();
  static const int kCopyGuidFieldNumber = 3;
  ::google::protobuf::int32 copyguid() const;
  void set_copyguid(::google::protobuf::int32 value);

  // int32 Carrer = 5;
  void clear_carrer();
  static const int kCarrerFieldNumber = 5;
  ::google::protobuf::int32 carrer() const;
  void set_carrer(::google::protobuf::int32 value);

  // int32 ActorID = 6;
  void clear_actorid();
  static const int kActorIDFieldNumber = 6;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // int32 Camp = 8;
  void clear_camp();
  static const int kCampFieldNumber = 8;
  ::google::protobuf::int32 camp() const;
  void set_camp(::google::protobuf::int32 value);

  // float X = 9;
  void clear_x();
  static const int kXFieldNumber = 9;
  float x() const;
  void set_x(float value);

  // float Y = 10;
  void clear_y();
  static const int kYFieldNumber = 10;
  float y() const;
  void set_y(float value);

  // float Z = 11;
  void clear_z();
  static const int kZFieldNumber = 11;
  float z() const;
  void set_z(float value);

  // float Ft = 12;
  void clear_ft();
  static const int kFtFieldNumber = 12;
  float ft() const;
  void set_ft(float value);

  // int32 Hp = 13;
  void clear_hp();
  static const int kHpFieldNumber = 13;
  ::google::protobuf::int32 hp() const;
  void set_hp(::google::protobuf::int32 value);

  // int32 Mp = 14;
  void clear_mp();
  static const int kMpFieldNumber = 14;
  ::google::protobuf::int32 mp() const;
  void set_mp(::google::protobuf::int32 value);

  // int32 HpMax = 15;
  void clear_hpmax();
  static const int kHpMaxFieldNumber = 15;
  ::google::protobuf::int32 hpmax() const;
  void set_hpmax(::google::protobuf::int32 value);

  // int32 MpMax = 16;
  void clear_mpmax();
  static const int kMpMaxFieldNumber = 16;
  ::google::protobuf::int32 mpmax() const;
  void set_mpmax(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:EnterSceneAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > equips_;
  mutable int _equips_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr rolename_;
  ::google::protobuf::uint32 retcode_;
  ::google::protobuf::int32 copyid_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::int32 copyguid_;
  ::google::protobuf::int32 carrer_;
  ::google::protobuf::int32 actorid_;
  ::google::protobuf::int32 camp_;
  float x_;
  float y_;
  float z_;
  float ft_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 mp_;
  ::google::protobuf::int32 hpmax_;
  ::google::protobuf::int32 mpmax_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fGame_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fGame_2eproto::InitDefaultsEnterSceneAckImpl();
};
// -------------------------------------------------------------------

class LeaveSceneReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LeaveSceneReq) */ {
 public:
  LeaveSceneReq();
  virtual ~LeaveSceneReq();

  LeaveSceneReq(const LeaveSceneReq& from);

  inline LeaveSceneReq& operator=(const LeaveSceneReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LeaveSceneReq(LeaveSceneReq&& from) noexcept
    : LeaveSceneReq() {
    *this = ::std::move(from);
  }

  inline LeaveSceneReq& operator=(LeaveSceneReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LeaveSceneReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LeaveSceneReq* internal_default_instance() {
    return reinterpret_cast<const LeaveSceneReq*>(
               &_LeaveSceneReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(LeaveSceneReq* other);
  friend void swap(LeaveSceneReq& a, LeaveSceneReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LeaveSceneReq* New() const PROTOBUF_FINAL { return New(NULL); }

  LeaveSceneReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LeaveSceneReq& from);
  void MergeFrom(const LeaveSceneReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LeaveSceneReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // int32 Reason = 2;
  void clear_reason();
  static const int kReasonFieldNumber = 2;
  ::google::protobuf::int32 reason() const;
  void set_reason(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LeaveSceneReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::int32 reason_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fGame_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fGame_2eproto::InitDefaultsLeaveSceneReqImpl();
};
// -------------------------------------------------------------------

class LeaveSceneAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LeaveSceneAck) */ {
 public:
  LeaveSceneAck();
  virtual ~LeaveSceneAck();

  LeaveSceneAck(const LeaveSceneAck& from);

  inline LeaveSceneAck& operator=(const LeaveSceneAck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LeaveSceneAck(LeaveSceneAck&& from) noexcept
    : LeaveSceneAck() {
    *this = ::std::move(from);
  }

  inline LeaveSceneAck& operator=(LeaveSceneAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LeaveSceneAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LeaveSceneAck* internal_default_instance() {
    return reinterpret_cast<const LeaveSceneAck*>(
               &_LeaveSceneAck_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(LeaveSceneAck* other);
  friend void swap(LeaveSceneAck& a, LeaveSceneAck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LeaveSceneAck* New() const PROTOBUF_FINAL { return New(NULL); }

  LeaveSceneAck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LeaveSceneAck& from);
  void MergeFrom(const LeaveSceneAck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LeaveSceneAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:LeaveSceneAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fGame_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fGame_2eproto::InitDefaultsLeaveSceneAckImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateNewSceneReq

// int32 CopyID = 1;
inline void CreateNewSceneReq::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneReq::copyid() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneReq.CopyID)
  return copyid_;
}
inline void CreateNewSceneReq::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneReq.CopyID)
}

// int32 CopyType = 2;
inline void CreateNewSceneReq::clear_copytype() {
  copytype_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneReq::copytype() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneReq.CopyType)
  return copytype_;
}
inline void CreateNewSceneReq::set_copytype(::google::protobuf::int32 value) {
  
  copytype_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneReq.CopyType)
}

// int32 PlayerNum = 3;
inline void CreateNewSceneReq::clear_playernum() {
  playernum_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneReq::playernum() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneReq.PlayerNum)
  return playernum_;
}
inline void CreateNewSceneReq::set_playernum(::google::protobuf::int32 value) {
  
  playernum_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneReq.PlayerNum)
}

// uint64 CreateParam = 4;
inline void CreateNewSceneReq::clear_createparam() {
  createparam_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CreateNewSceneReq::createparam() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneReq.CreateParam)
  return createparam_;
}
inline void CreateNewSceneReq::set_createparam(::google::protobuf::uint64 value) {
  
  createparam_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneReq.CreateParam)
}

// -------------------------------------------------------------------

// CreateNewSceneAck

// uint32 RetCode = 1;
inline void CreateNewSceneAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 CreateNewSceneAck::retcode() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.RetCode)
  return retcode_;
}
inline void CreateNewSceneAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.RetCode)
}

// int32 CopyID = 2;
inline void CreateNewSceneAck::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneAck::copyid() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.CopyID)
  return copyid_;
}
inline void CreateNewSceneAck::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.CopyID)
}

// int32 CopyGuid = 3;
inline void CreateNewSceneAck::clear_copyguid() {
  copyguid_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneAck::copyguid() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.CopyGuid)
  return copyguid_;
}
inline void CreateNewSceneAck::set_copyguid(::google::protobuf::int32 value) {
  
  copyguid_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.CopyGuid)
}

// uint64 CreateParam = 4;
inline void CreateNewSceneAck::clear_createparam() {
  createparam_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CreateNewSceneAck::createparam() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.CreateParam)
  return createparam_;
}
inline void CreateNewSceneAck::set_createparam(::google::protobuf::uint64 value) {
  
  createparam_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.CreateParam)
}

// int32 ServerID = 5;
inline void CreateNewSceneAck::clear_serverid() {
  serverid_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneAck::serverid() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.ServerID)
  return serverid_;
}
inline void CreateNewSceneAck::set_serverid(::google::protobuf::int32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.ServerID)
}

// int32 CopyType = 6;
inline void CreateNewSceneAck::clear_copytype() {
  copytype_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneAck::copytype() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.CopyType)
  return copytype_;
}
inline void CreateNewSceneAck::set_copytype(::google::protobuf::int32 value) {
  
  copytype_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.CopyType)
}

// int32 PlayerNum = 7;
inline void CreateNewSceneAck::clear_playernum() {
  playernum_ = 0;
}
inline ::google::protobuf::int32 CreateNewSceneAck::playernum() const {
  // @@protoc_insertion_point(field_get:CreateNewSceneAck.PlayerNum)
  return playernum_;
}
inline void CreateNewSceneAck::set_playernum(::google::protobuf::int32 value) {
  
  playernum_ = value;
  // @@protoc_insertion_point(field_set:CreateNewSceneAck.PlayerNum)
}

// -------------------------------------------------------------------

// EnterSceneReq

// uint64 RoleID = 1;
inline void EnterSceneReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 EnterSceneReq::roleid() const {
  // @@protoc_insertion_point(field_get:EnterSceneReq.RoleID)
  return roleid_;
}
inline void EnterSceneReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneReq.RoleID)
}

// int32 ServerID = 2;
inline void EnterSceneReq::clear_serverid() {
  serverid_ = 0;
}
inline ::google::protobuf::int32 EnterSceneReq::serverid() const {
  // @@protoc_insertion_point(field_get:EnterSceneReq.ServerID)
  return serverid_;
}
inline void EnterSceneReq::set_serverid(::google::protobuf::int32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneReq.ServerID)
}

// int32 CopyGuid = 3;
inline void EnterSceneReq::clear_copyguid() {
  copyguid_ = 0;
}
inline ::google::protobuf::int32 EnterSceneReq::copyguid() const {
  // @@protoc_insertion_point(field_get:EnterSceneReq.CopyGuid)
  return copyguid_;
}
inline void EnterSceneReq::set_copyguid(::google::protobuf::int32 value) {
  
  copyguid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneReq.CopyGuid)
}

// int32 CopyID = 4;
inline void EnterSceneReq::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 EnterSceneReq::copyid() const {
  // @@protoc_insertion_point(field_get:EnterSceneReq.CopyID)
  return copyid_;
}
inline void EnterSceneReq::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneReq.CopyID)
}

// -------------------------------------------------------------------

// EnterSceneAck

// uint32 RetCode = 1;
inline void EnterSceneAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 EnterSceneAck::retcode() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.RetCode)
  return retcode_;
}
inline void EnterSceneAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.RetCode)
}

// int32 CopyID = 2;
inline void EnterSceneAck::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::copyid() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.CopyID)
  return copyid_;
}
inline void EnterSceneAck::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.CopyID)
}

// int32 CopyGuid = 3;
inline void EnterSceneAck::clear_copyguid() {
  copyguid_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::copyguid() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.CopyGuid)
  return copyguid_;
}
inline void EnterSceneAck::set_copyguid(::google::protobuf::int32 value) {
  
  copyguid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.CopyGuid)
}

// uint64 RoleID = 4;
inline void EnterSceneAck::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 EnterSceneAck::roleid() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.RoleID)
  return roleid_;
}
inline void EnterSceneAck::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.RoleID)
}

// int32 Carrer = 5;
inline void EnterSceneAck::clear_carrer() {
  carrer_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::carrer() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Carrer)
  return carrer_;
}
inline void EnterSceneAck::set_carrer(::google::protobuf::int32 value) {
  
  carrer_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Carrer)
}

// int32 ActorID = 6;
inline void EnterSceneAck::clear_actorid() {
  actorid_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::actorid() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.ActorID)
  return actorid_;
}
inline void EnterSceneAck::set_actorid(::google::protobuf::int32 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.ActorID)
}

// string RoleName = 7;
inline void EnterSceneAck::clear_rolename() {
  rolename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& EnterSceneAck::rolename() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.RoleName)
  return rolename_.GetNoArena();
}
inline void EnterSceneAck::set_rolename(const ::std::string& value) {
  
  rolename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:EnterSceneAck.RoleName)
}
#if LANG_CXX11
inline void EnterSceneAck::set_rolename(::std::string&& value) {
  
  rolename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:EnterSceneAck.RoleName)
}
#endif
inline void EnterSceneAck::set_rolename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  rolename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:EnterSceneAck.RoleName)
}
inline void EnterSceneAck::set_rolename(const char* value, size_t size) {
  
  rolename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:EnterSceneAck.RoleName)
}
inline ::std::string* EnterSceneAck::mutable_rolename() {
  
  // @@protoc_insertion_point(field_mutable:EnterSceneAck.RoleName)
  return rolename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* EnterSceneAck::release_rolename() {
  // @@protoc_insertion_point(field_release:EnterSceneAck.RoleName)
  
  return rolename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void EnterSceneAck::set_allocated_rolename(::std::string* rolename) {
  if (rolename != NULL) {
    
  } else {
    
  }
  rolename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rolename);
  // @@protoc_insertion_point(field_set_allocated:EnterSceneAck.RoleName)
}

// int32 Camp = 8;
inline void EnterSceneAck::clear_camp() {
  camp_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::camp() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Camp)
  return camp_;
}
inline void EnterSceneAck::set_camp(::google::protobuf::int32 value) {
  
  camp_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Camp)
}

// float X = 9;
inline void EnterSceneAck::clear_x() {
  x_ = 0;
}
inline float EnterSceneAck::x() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.X)
  return x_;
}
inline void EnterSceneAck::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.X)
}

// float Y = 10;
inline void EnterSceneAck::clear_y() {
  y_ = 0;
}
inline float EnterSceneAck::y() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Y)
  return y_;
}
inline void EnterSceneAck::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Y)
}

// float Z = 11;
inline void EnterSceneAck::clear_z() {
  z_ = 0;
}
inline float EnterSceneAck::z() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Z)
  return z_;
}
inline void EnterSceneAck::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Z)
}

// float Ft = 12;
inline void EnterSceneAck::clear_ft() {
  ft_ = 0;
}
inline float EnterSceneAck::ft() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Ft)
  return ft_;
}
inline void EnterSceneAck::set_ft(float value) {
  
  ft_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Ft)
}

// int32 Hp = 13;
inline void EnterSceneAck::clear_hp() {
  hp_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::hp() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Hp)
  return hp_;
}
inline void EnterSceneAck::set_hp(::google::protobuf::int32 value) {
  
  hp_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Hp)
}

// int32 Mp = 14;
inline void EnterSceneAck::clear_mp() {
  mp_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::mp() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Mp)
  return mp_;
}
inline void EnterSceneAck::set_mp(::google::protobuf::int32 value) {
  
  mp_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.Mp)
}

// int32 HpMax = 15;
inline void EnterSceneAck::clear_hpmax() {
  hpmax_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::hpmax() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.HpMax)
  return hpmax_;
}
inline void EnterSceneAck::set_hpmax(::google::protobuf::int32 value) {
  
  hpmax_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.HpMax)
}

// int32 MpMax = 16;
inline void EnterSceneAck::clear_mpmax() {
  mpmax_ = 0;
}
inline ::google::protobuf::int32 EnterSceneAck::mpmax() const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.MpMax)
  return mpmax_;
}
inline void EnterSceneAck::set_mpmax(::google::protobuf::int32 value) {
  
  mpmax_ = value;
  // @@protoc_insertion_point(field_set:EnterSceneAck.MpMax)
}

// repeated int32 Equips = 17;
inline int EnterSceneAck::equips_size() const {
  return equips_.size();
}
inline void EnterSceneAck::clear_equips() {
  equips_.Clear();
}
inline ::google::protobuf::int32 EnterSceneAck::equips(int index) const {
  // @@protoc_insertion_point(field_get:EnterSceneAck.Equips)
  return equips_.Get(index);
}
inline void EnterSceneAck::set_equips(int index, ::google::protobuf::int32 value) {
  equips_.Set(index, value);
  // @@protoc_insertion_point(field_set:EnterSceneAck.Equips)
}
inline void EnterSceneAck::add_equips(::google::protobuf::int32 value) {
  equips_.Add(value);
  // @@protoc_insertion_point(field_add:EnterSceneAck.Equips)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
EnterSceneAck::equips() const {
  // @@protoc_insertion_point(field_list:EnterSceneAck.Equips)
  return equips_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
EnterSceneAck::mutable_equips() {
  // @@protoc_insertion_point(field_mutable_list:EnterSceneAck.Equips)
  return &equips_;
}

// -------------------------------------------------------------------

// LeaveSceneReq

// uint64 RoleID = 1;
inline void LeaveSceneReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LeaveSceneReq::roleid() const {
  // @@protoc_insertion_point(field_get:LeaveSceneReq.RoleID)
  return roleid_;
}
inline void LeaveSceneReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:LeaveSceneReq.RoleID)
}

// int32 Reason = 2;
inline void LeaveSceneReq::clear_reason() {
  reason_ = 0;
}
inline ::google::protobuf::int32 LeaveSceneReq::reason() const {
  // @@protoc_insertion_point(field_get:LeaveSceneReq.Reason)
  return reason_;
}
inline void LeaveSceneReq::set_reason(::google::protobuf::int32 value) {
  
  reason_ = value;
  // @@protoc_insertion_point(field_set:LeaveSceneReq.Reason)
}

// -------------------------------------------------------------------

// LeaveSceneAck

// uint32 RetCode = 1;
inline void LeaveSceneAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 LeaveSceneAck::retcode() const {
  // @@protoc_insertion_point(field_get:LeaveSceneAck.RetCode)
  return retcode_;
}
inline void LeaveSceneAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:LeaveSceneAck.RetCode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fGame_2eproto__INCLUDED
