// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_RetCode.proto

#include "Msg_RetCode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class ServerPingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerPing>
      _instance;
} _ServerPing_default_instance_;
namespace protobuf_Msg_5fRetCode_2eproto {
void InitDefaultsServerPingImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  {
    void* ptr = &::_ServerPing_default_instance_;
    new (ptr) ::ServerPing();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ServerPing::InitAsDefaultInstance();
}

void InitDefaultsServerPing() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsServerPingImpl);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ServerPing, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ServerPing, servertime_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ServerPing)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ServerPing_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Msg_RetCode.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021Msg_RetCode.proto\" \n\nServerPing\022\022\n\nser"
      "vertime\030\001 \001(\004*\324\002\n\016MessageRetCode\022\021\n\rMRC_"
      "SUCCESSED\020\000\022\024\n\020MRC_UNKNOW_ERROR\020\001\022\022\n\016MRC"
      "_DISCONNECT\020\002\022\025\n\021MRC_ACCOUNT_EXIST\020\003\022\022\n\016"
      "MRC_NAME_EXIST\020\004\022\026\n\022MRC_ACCOUNT_SEALED\020\005"
      "\022\026\n\022MRC_ACCOUNTISLOGIN\020\006\022\032\n\026MRC_ROOM_CRE"
      "ATE_FAILED\020\007\022\026\n\022MRC_NOT_FOUND_ROOM\020\010\022\027\n\023"
      "MRC_INVALID_ACCNAME\020d\022\025\n\021MRC_INVALID_ACC"
      "ID\020e\022\030\n\024MRC_INVALID_PASSWORD\020f\022\024\n\020MRC_IN"
      "VALID_NAME\020g\022\026\n\022MRC_INVALID_ROLEID\020hb\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 404);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Msg_RetCode.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Msg_5fRetCode_2eproto
const ::google::protobuf::EnumDescriptor* MessageRetCode_descriptor() {
  protobuf_Msg_5fRetCode_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Msg_5fRetCode_2eproto::file_level_enum_descriptors[0];
}
bool MessageRetCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ServerPing::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerPing::kServertimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerPing::ServerPing()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_Msg_5fRetCode_2eproto::InitDefaultsServerPing();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerPing)
}
ServerPing::ServerPing(const ServerPing& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  servertime_ = from.servertime_;
  // @@protoc_insertion_point(copy_constructor:ServerPing)
}

void ServerPing::SharedCtor() {
  servertime_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

ServerPing::~ServerPing() {
  // @@protoc_insertion_point(destructor:ServerPing)
  SharedDtor();
}

void ServerPing::SharedDtor() {
}

void ServerPing::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServerPing::descriptor() {
  ::protobuf_Msg_5fRetCode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Msg_5fRetCode_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerPing& ServerPing::default_instance() {
  ::protobuf_Msg_5fRetCode_2eproto::InitDefaultsServerPing();
  return *internal_default_instance();
}

ServerPing* ServerPing::New(::google::protobuf::Arena* arena) const {
  ServerPing* n = new ServerPing;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ServerPing::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerPing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  servertime_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool ServerPing::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerPing)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 servertime = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &servertime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerPing)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerPing)
  return false;
#undef DO_
}

void ServerPing::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerPing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 servertime = 1;
  if (this->servertime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->servertime(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ServerPing)
}

::google::protobuf::uint8* ServerPing::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ServerPing)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 servertime = 1;
  if (this->servertime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->servertime(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ServerPing)
  return target;
}

size_t ServerPing::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerPing)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 servertime = 1;
  if (this->servertime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->servertime());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ServerPing::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ServerPing)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerPing* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ServerPing>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ServerPing)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ServerPing)
    MergeFrom(*source);
  }
}

void ServerPing::MergeFrom(const ServerPing& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ServerPing)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.servertime() != 0) {
    set_servertime(from.servertime());
  }
}

void ServerPing::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ServerPing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerPing::CopyFrom(const ServerPing& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerPing)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerPing::IsInitialized() const {
  return true;
}

void ServerPing::Swap(ServerPing* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerPing::InternalSwap(ServerPing* other) {
  using std::swap;
  swap(servertime_, other->servertime_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ServerPing::GetMetadata() const {
  protobuf_Msg_5fRetCode_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Msg_5fRetCode_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
