// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_RetCode.proto

#ifndef PROTOBUF_Msg_5fRetCode_2eproto__INCLUDED
#define PROTOBUF_Msg_5fRetCode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Msg_5fRetCode_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsServerPingImpl();
void InitDefaultsServerPing();
inline void InitDefaults() {
  InitDefaultsServerPing();
}
}  // namespace protobuf_Msg_5fRetCode_2eproto
class ServerPing;
class ServerPingDefaultTypeInternal;
extern ServerPingDefaultTypeInternal _ServerPing_default_instance_;

enum MessageRetCode {
  MRC_SUCCESSED = 0,
  MRC_UNKNOW_ERROR = 1,
  MRC_DISCONNECT = 2,
  MRC_ACCOUNT_EXIST = 3,
  MRC_NAME_EXIST = 4,
  MRC_ACCOUNT_SEALED = 5,
  MRC_ACCOUNTISLOGIN = 6,
  MRC_ROOM_CREATE_FAILED = 7,
  MRC_NOT_FOUND_ROOM = 8,
  MRC_INVALID_ACCNAME = 100,
  MRC_INVALID_ACCID = 101,
  MRC_INVALID_PASSWORD = 102,
  MRC_INVALID_NAME = 103,
  MRC_INVALID_ROLEID = 104,
  MessageRetCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageRetCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageRetCode_IsValid(int value);
const MessageRetCode MessageRetCode_MIN = MRC_SUCCESSED;
const MessageRetCode MessageRetCode_MAX = MRC_INVALID_ROLEID;
const int MessageRetCode_ARRAYSIZE = MessageRetCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageRetCode_descriptor();
inline const ::std::string& MessageRetCode_Name(MessageRetCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageRetCode_descriptor(), value);
}
inline bool MessageRetCode_Parse(
    const ::std::string& name, MessageRetCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageRetCode>(
    MessageRetCode_descriptor(), name, value);
}
// ===================================================================

class ServerPing : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerPing) */ {
 public:
  ServerPing();
  virtual ~ServerPing();

  ServerPing(const ServerPing& from);

  inline ServerPing& operator=(const ServerPing& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerPing(ServerPing&& from) noexcept
    : ServerPing() {
    *this = ::std::move(from);
  }

  inline ServerPing& operator=(ServerPing&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerPing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerPing* internal_default_instance() {
    return reinterpret_cast<const ServerPing*>(
               &_ServerPing_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ServerPing* other);
  friend void swap(ServerPing& a, ServerPing& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerPing* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerPing* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerPing& from);
  void MergeFrom(const ServerPing& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerPing* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 servertime = 1;
  void clear_servertime();
  static const int kServertimeFieldNumber = 1;
  ::google::protobuf::uint64 servertime() const;
  void set_servertime(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:ServerPing)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 servertime_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fRetCode_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fRetCode_2eproto::InitDefaultsServerPingImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerPing

// uint64 servertime = 1;
inline void ServerPing::clear_servertime() {
  servertime_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ServerPing::servertime() const {
  // @@protoc_insertion_point(field_get:ServerPing.servertime)
  return servertime_;
}
inline void ServerPing::set_servertime(::google::protobuf::uint64 value) {
  
  servertime_ = value;
  // @@protoc_insertion_point(field_set:ServerPing.servertime)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MessageRetCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageRetCode>() {
  return ::MessageRetCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fRetCode_2eproto__INCLUDED
