//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: proto_raw/Msg_ID.proto
namespace Proto
{
    [global::ProtoBuf.ProtoContract(Name=@"MessageID")]
    public enum MessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BEGIN", Value=0)]
      MSG_BEGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BATTLE_BEGIN", Value=30000)]
      MSG_BATTLE_BEGIN = 30000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CLIENT_LOGIN_GS_REQ", Value=30001)]
      MSG_CLIENT_LOGIN_GS_REQ = 30001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CLIENT_LOGIN_GS_ACK", Value=30002)]
      MSG_CLIENT_LOGIN_GS_ACK = 30002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CREATE_ROOM_REQ", Value=30003)]
      MSG_CREATE_ROOM_REQ = 30003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CREATE_ROOM_ACK", Value=30004)]
      MSG_CREATE_ROOM_ACK = 30004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FINDPATH_REQ", Value=30005)]
      MSG_FINDPATH_REQ = 30005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FINDPATH_ACK", Value=30006)]
      MSG_FINDPATH_ACK = 30006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_BATTLE_END", Value=32000)]
      MSG_BATTLE_END = 32000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_MSGID_BEGIN", Value=58000)]
      MSG_AI_MSGID_BEGIN = 58000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GS_REGISTER_AISVR_REQ", Value=58001)]
      MSG_GS_REGISTER_AISVR_REQ = 58001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_GS_REGISTER_AISVR_ACK", Value=58002)]
      MSG_GS_REGISTER_AISVR_ACK = 58002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_MSGID_END", Value=60000)]
      MSG_AI_MSGID_END = 60000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_PING", Value=65530)]
      MSG_PING = 65530,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_END", Value=65535)]
      MSG_END = 65535
    }
  
}