//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: proto_raw/Msg_RetCode.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerPing")]
  public partial class ServerPing : global::ProtoBuf.IExtensible
  {
    public ServerPing() {}
    
    private ulong? _servertime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"servertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong servertime
    {
      get { return _servertime?? default(ulong); }
      set { _servertime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool servertimeSpecified
    {
      get { return this._servertime != null; }
      set { if (value == (this._servertime== null)) this._servertime = value ? this.servertime : (ulong?)null; }
    }
    private bool ShouldSerializeservertime() { return servertimeSpecified; }
    private void Resetservertime() { servertimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageRetCode")]
    public enum MessageRetCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRC_SUCCESSED", Value=0)]
      MRC_SUCCESSED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRC_UNKNOW_ERROR", Value=1)]
      MRC_UNKNOW_ERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRC_DISCONNECT", Value=2)]
      MRC_DISCONNECT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRC_ACCOUNTISLOGIN", Value=3)]
      MRC_ACCOUNTISLOGIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRC_ROOM_CREATE_FAILED", Value=4)]
      MRC_ROOM_CREATE_FAILED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRC_NOT_FOUND_ROOM", Value=5)]
      MRC_NOT_FOUND_ROOM = 5
    }
  
}