//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: proto_raw/Msg_AI.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SvrRegToSvrReq")]
  public partial class SvrRegToSvrReq : global::ProtoBuf.IExtensible
  {
    public SvrRegToSvrReq() {}
    
    private int? _ServerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerID
    {
      get { return _ServerID?? default(int); }
      set { _ServerID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ServerIDSpecified
    {
      get { return this._ServerID != null; }
      set { if (value == (this._ServerID== null)) this._ServerID = value ? this.ServerID : (int?)null; }
    }
    private bool ShouldSerializeServerID() { return ServerIDSpecified; }
    private void ResetServerID() { ServerIDSpecified = false; }
    
    private string _ServerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ServerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerName
    {
      get { return _ServerName?? ""; }
      set { _ServerName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ServerNameSpecified
    {
      get { return this._ServerName != null; }
      set { if (value == (this._ServerName== null)) this._ServerName = value ? this.ServerName : (string)null; }
    }
    private bool ShouldSerializeServerName() { return ServerNameSpecified; }
    private void ResetServerName() { ServerNameSpecified = false; }
    
    private string _ServerIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerIp
    {
      get { return _ServerIp?? ""; }
      set { _ServerIp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ServerIpSpecified
    {
      get { return this._ServerIp != null; }
      set { if (value == (this._ServerIp== null)) this._ServerIp = value ? this.ServerIp : (string)null; }
    }
    private bool ShouldSerializeServerIp() { return ServerIpSpecified; }
    private void ResetServerIp() { ServerIpSpecified = false; }
    
    private int? _ServerPort;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerPort
    {
      get { return _ServerPort?? default(int); }
      set { _ServerPort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ServerPortSpecified
    {
      get { return this._ServerPort != null; }
      set { if (value == (this._ServerPort== null)) this._ServerPort = value ? this.ServerPort : (int?)null; }
    }
    private bool ShouldSerializeServerPort() { return ServerPortSpecified; }
    private void ResetServerPort() { ServerPortSpecified = false; }
    
    private int? _HttpPort;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"HttpPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int HttpPort
    {
      get { return _HttpPort?? default(int); }
      set { _HttpPort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool HttpPortSpecified
    {
      get { return this._HttpPort != null; }
      set { if (value == (this._HttpPort== null)) this._HttpPort = value ? this.HttpPort : (int?)null; }
    }
    private bool ShouldSerializeHttpPort() { return HttpPortSpecified; }
    private void ResetHttpPort() { HttpPortSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SvrRegToSvrAck")]
  public partial class SvrRegToSvrAck : global::ProtoBuf.IExtensible
  {
    public SvrRegToSvrAck() {}
    
    private int? _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode?? default(int); }
      set { _RetCode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RetCodeSpecified
    {
      get { return this._RetCode != null; }
      set { if (value == (this._RetCode== null)) this._RetCode = value ? this.RetCode : (int?)null; }
    }
    private bool ShouldSerializeRetCode() { return RetCodeSpecified; }
    private void ResetRetCode() { RetCodeSpecified = false; }
    
    private string _NewSvrName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NewSvrName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NewSvrName
    {
      get { return _NewSvrName?? ""; }
      set { _NewSvrName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NewSvrNameSpecified
    {
      get { return this._NewSvrName != null; }
      set { if (value == (this._NewSvrName== null)) this._NewSvrName = value ? this.NewSvrName : (string)null; }
    }
    private bool ShouldSerializeNewSvrName() { return NewSvrNameSpecified; }
    private void ResetNewSvrName() { NewSvrNameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}